apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: nginx
  name: nginx-deploy-main
spec:
  replicas: 1
  selector:
    matchLabels:
      run: nginx-main
  template:
    metadata:
      labels:
        run: nginx-main
    spec:
      containers:
      - name: nginx
        image: 421320058418.dkr.ecr.us-east-2.amazonaws.com/nginx-base-image:v1
        command:
          - /bin/sh
          - -c
          - while sleep 300; do date >> /secondary/secondary.txt && curl google.com >> /secondary/secondary.txt; done
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 256m
            memory: 128Mi
        volumeMounts:
          - name: efs-storage-volume
            mountPath: /secondary
      volumes:
        - name: efs-storage-volume
          persistentVolumeClaim:
            claimName: efs-pvc-secondary
       
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-main
  labels:
    run: nginx
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: nginx-main